// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    App: typeof import('./../../App.vue')['default']
    AsideNav: typeof import('./../../layout/components/AsideNav/index.vue')['default']
    Auto: typeof import('./../../views/marketing/auto/index.vue')['default']
    Card: typeof import('./../../views/setting/card/index.vue')['default']
    Code: typeof import('./../../views/setting/code/index.vue')['default']
    ConsumptionItem: typeof import('./../../views/member/components/ConsumptionItem.vue')['default']
    CreateCode: typeof import('./../../views/setting/code/CreateCode.vue')['default']
    CreateItem: typeof import('./../../views/setting/material/CreateItem.vue')['default']
    CreateMember: typeof import('./../../views/member/components/CreateMember.vue')['default']
    CreateRule: typeof import('./../../views/marketing/auto/CreateRule.vue')['default']
    CreateStore: typeof import('./../../views/login/components/CreateStore.vue')['default']
    CreateTags: typeof import('./../../views/tags/CreateTags.vue')['default']
    CreateTemplate: typeof import('./../../views/marketing/template/CreateTemplate.vue')['default']
    CreateUser: typeof import('./../../views/login/components/CreateUser.vue')['default']
    CropperDialog: typeof import('./../../components/CropperDialog.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    HeaderBar: typeof import('./../../layout/components/HeaderBar.vue')['default']
    IconSvg: typeof import('./../../components/IconSvg.vue')['default']
    ImportUser: typeof import('./../../views/member/components/ImportUser.vue')['default']
    Layout: typeof import('./../../layout/index.vue')['default']
    Login: typeof import('./../../views/login/index.vue')['default']
    Manual: typeof import('./../../views/marketing/manual/index.vue')['default']
    Material: typeof import('./../../views/setting/material/index.vue')['default']
    Member: typeof import('./../../views/member/index.vue')['default']
    MemberCard: typeof import('./../../components/MemberCard.vue')['default']
    MemberCoupon: typeof import('./../../components/MemberCoupon.vue')['default']
    MemberDetail: typeof import('./../../views/member/components/MemberDetail.vue')['default']
    MemberSearch: typeof import('./../../components/MemberSearch.vue')['default']
    MenuItem: typeof import('./../../layout/components/AsideNav/MenuItem.vue')['default']
    MessageType: typeof import('./../../components/MessageType.vue')['default']
    NutcardsCode: typeof import('./../../components/NutcardsCode.vue')['default']
    QuickSearch: typeof import('./../../views/member/components/QuickSearch.vue')['default']
    Record: typeof import('./../../views/marketing/record/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SetTags: typeof import('./../../views/member/components/SetTags.vue')['default']
    SubMenuItem: typeof import('./../../layout/components/AsideNav/SubMenuItem.vue')['default']
    SuccessDialog: typeof import('./../../views/login/components/SuccessDialog.vue')['default']
    Tags: typeof import('./../../views/tags/index.vue')['default']
    Template: typeof import('./../../views/marketing/template/index.vue')['default']
    UploadFile: typeof import('./../../components/UploadFile.vue')['default']
  }
}
